
checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 8.1
    tests:
        override:
            - command: 'XDEBUG_MODE=coverage vendor/bin/phpunit -d xdebug.mode=coverage --coverage-clover=some-file'
              coverage:
                file: 'some-file'
                format: 'clover'

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
